---
- name: Setup Microk8s
  hosts: all
  become: true
  tasks:
    - name: Setup tools
      shell: "sudo apt-get install snapd"
      args:
        executable: /bin/bash

    - name: Install microk8s
      shell: "sudo snap install microk8s --classic"
      args:
        executable: /bin/bash

    - name: usermod microk8s
      shell: "sudo usermod -aG microk8s ubuntu"
      args:
        executable: /bin/bash

    - name: chown
      shell: "sudo chown -fR ubuntu ~/.kube"
      args:
        executable: /bin/bash
        
    - name: kubectl alias
      shell: "sudo snap alias microk8s.kubectl kubectl"
      args:
        executable: /bin/bash
        
    - name: kubectl alias
      shell: "newgrp microk8s"
      args:
        executable: /bin/bash
